# Generated by Django 5.1.4 on 2025-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_package_Mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inforTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('ìnforcompany', models.CharField(max_length=255)),
                ('inforprices', models.FloatField()),
                ('service', models.CharField(max_length=255)),
            ],
        ),
    ]
