# Generated by Django 5.1.5 on 2025-01-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_package_Mng', '0006_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='Không có số', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
    ]
